/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Conexion;
import modelo.Usuarios;
import static vista.Cambio_Contraseña.con;


/**
 *
 * @author Diana
 */
public class CambioClave extends javax.swing.JFrame {

    static Connection con=null;
    int x,y;
    private String pass;
    private String Usuarios;
    /**
     * Creates new form CambioClave
     */
    public CambioClave() {
        initComponents();
 //         setLocalRelativeTo(null);
       jPasswordNew.requestFocus();
    }
//    
//     void Cambio_Contraseña(){
//        String clavevacia=jPasswordNew.getText();
//        String confivacia=jpassconfirmclave.getText();
//        
//         if(("".equals(clavevacia)) || ("".equals(confivacia))){
//            JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
//            jPasswordNew.requestFocus();
//        
//    }else {  
//             if (jPasswordNew.getText().equals(jpassconfirmclave.getText())){                
//        int resp=JOptionPane.showConfirmDialog(null, "Confirmar Contraseña","pregunta",0);
//        
//        if(resp==0){           
//            String cont=jPasswordNew.getText();      
//         try {
//             
//             
//         //   Connection cn= DriverManager.getConnection("jdbc:mysql://localhost/usuarios","root","");
//             String sql= "UPDATE usuarios set pass_usu=? where usuario=?";
//           
//              PreparedStatement pst= con.prepareCall(sql);
//          
//            pst.setString(1, cont);
//            pst.setString(2, Recuperacio.ced1 );
//            
//            int a = pst.executeUpdate();
//            JOptionPane.showMessageDialog(null,"Contraseña nueva aceptada");
//        } catch( SQLException  | HeadlessException e ){
//            }  
//        
//            dispose();
//            
//             Inicio  a = new Inicio();
//                a.setVisible(true);
//            
//    } }  else {
//            
//            JOptionPane.showMessageDialog(null, " Las contrañas no coinciden");
//            
//            
//            }
//}}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordNew = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Label_status = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpassconfirmclave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogin.setText("Aceptar");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Escriba su nueva contraseña");

        jLabel2.setText("Nueva Contraseña");

        jLabel3.setText("Confirmar Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(8, 8, 8)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPasswordNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(jpassconfirmclave))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLogin)
                            .addComponent(Label_status))))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpassconfirmclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addComponent(btnLogin)
                .addGap(10, 10, 10)
                .addComponent(Label_status)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("deprecation")
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

// *************************************MODIFICAR/ACEPTAR************************************************************************
//        Cambio_Contraseña(); 
//  try {
//            String ID = txtid.getText().trim();
//
//            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Usuarios", "root", "");
//            PreparedStatement pst = cn.prepareStatement("update usuarios set  password = ? where usuario = " + ID);
//
//            pst.setString(1, jPasswordNew.getText().trim());
//           
//            pst.executeUpdate();
//
//            Label_status.setText("Modificación exitosa.");
//
//        } catch (Exception e) {
//        }
  
 //********************************************************************************************************************************
  
String sSQL = "";
Conexion mysql = new Conexion();
Connection cn = mysql.getConexion();
String  pas,pasn;

pas= jPasswordNew.getText();
pasn=jpassconfirmclave.getText();
 
sSQL = "UPDATE usuarios " +"SET password = ?"  +"WHERE id = "+ Usuarios;
/** id_actualizar es una variable de clase y se implementa en el metodo BuscarEditar(String id) donde toma el valor del parametro de dicho metodo*/
String mensaje = "Los contaseña se ha Cambiado de Manera Satisfactoria...";

try{
        String clavevacia=jPasswordNew.getText();
        String confivacia=jpassconfirmclave.getText();
         if(("".equals(clavevacia)) || ("".equals(confivacia))){
            JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
            jPasswordNew.requestFocus();
    }else {
             if (jPasswordNew.getText().equals(jpassconfirmclave.getText())){
      
        int resp=JOptionPane.showConfirmDialog(null, "Confirmar Contraseña","pregunta",0);
        
        if(resp==0){
            
            String cont=jPasswordNew.getText();
            
//    PreparedStatement pst= con.prepareCall(sSQL);
PreparedStatement pst = cn.prepareStatement(sSQL);// con esta sentencia se insertan los datos en la base de datos
pst.setString(1, cont);
 pst.setString(2, Recuperacio.ced1 );

int n = pst.executeUpdate();//valida si se guardaron los datos; 
{
}
}
      }
             }
         }catch (SQLException ex){
    
         Logger.getLogger(CambioClave.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, ex);

      dispose();
            
             Inicio  a = new Inicio();
                a.setVisible(true);
            

            
            JOptionPane.showMessageDialog(null, " Las contrañas no coinciden");
        
        
        
        
        
        
        
        
        
        
//         try {
//             
//             
//         //   Connection cn= DriverManager.getConnection("jdbc:mysql://localhost/usuarios","root","");
//             String sql= "UPDATE usuarios set pass_usu=? where usuario=?";
//           
//              PreparedStatement pst= con.prepareCall(sql);
//          
//            pst.setString(1, cont);
//            pst.setString(2, Recuperacio.ced1 );
//            
//            int a = pst.executeUpdate();
//            JOptionPane.showMessageDialog(null,"Contraseña nueva aceptada");
//        } catch( SQLException  | HeadlessException e ){
//            }  
//        
//            dispose();
//            
//             Inicio  a = new Inicio();
//                a.setVisible(true);
//            
//    } }  else {
//            
//            JOptionPane.showMessageDialog(null, " Las contrañas no coinciden");
//            
//            
         //   }
  //  catch (SQLException ex) {
           
        }


    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioClave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_status;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordNew;
    private javax.swing.JPasswordField jpassconfirmclave;
    // End of variables declaration//GEN-END:variables

  }