
package vista;

import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import modelo.Hash;
import modelo.SqlUsuarios;
import modelo.Usuarios;


/**
 *
 * @author Diana
 */
public class Recuperacio extends javax.swing.JFrame {

    public static String resp="";
        public static String ced1="";
        int x,y;
        static Connection con=null;
    /**
     * Creates new form Recuperacio
     */
    public Recuperacio() {
        initComponents();
//               setLocalRelativeTo(null);
       txtid.requestFocus();
    }

  //***************************************************************************************************************

//CONFIRMAR USUARIO    
    
    void Confirmar_Usuario(){
          
        String ced_tra = txtid.getText();
       
        try{
            if ("".equals((ced_tra)))
            {
                    JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
                    txtid.requestFocus();       
            }else{
                   // con =Connection.Conexion.Conexion;
                    
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost/Usuarios","root","");   
//                String sql= "SELECT * FROM usuarios WHERE usuario='" + txtusuario.getText() + "'";
////                                     Statement st=con.createStatement();
            PreparedStatement pst = cn.prepareStatement("select * from usuarios where usuario = ?");
            pst.setString(1, txtid.getText().trim());
            ResultSet rs = pst.executeQuery();

        //    PreparedStatement pst = cn.prepareStatement("select * from usuarios where usuario = ?");
         //   pst.setString(1, txtusuario.getText().trim());

  //          ResultSet rs = pst.executeQuery();

              //busca
             //  ResultSet rs = st.executeQuery(sql);
                String preg="";
                String cedu="";
                
                if (rs.next()){
                    //busca
                    cedu=rs.getString("usuario");
                    preg=rs.getString("pregunta");
                 //   Recuperacio.resp= rs.getString("respuesta");
                     
                   
                } else {
                    JOptionPane.showConfirmDialog(null, "Nombre de Usuario Incorrecto");
                    txtid.setText("");
                    txtid.requestFocus();
                }
 //**********************************************************************************************************
                //CONFIGURACION DE PREGUNTA EN EL PANEL 
//                Recuperacio.ced1=cedu;
//                jpanel_pregun_pane.removeAll();
//                jpanel_pregun_pane.updateUI();
//                jpanel_pregun_pane.repaint();                
//                this.validate(); 
//                lblpregunta.setText(preg);
//                jpanel_pregun_pane.setLayout(new GridLayout(1,1));
//                jpanel_pregun_pane.add(lblpregunta);             
            }}catch(SQLException | HeadlessException e){          
        } } 
    
//    ***************************************************************************************************
       
    void Confirmar_Respuesta(){
//        
          
        String  ced_trans = txtid.getText();
    //    String  pregunta = lblpregunta.getText();
        String  respuesta = txtRespuesta.getText();
        
        if(("".equals(ced_trans)) ||  ("".equals(respuesta)))
        {
            
            JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
            txtRespuesta.requestFocus();
            
        } else {
            
            if(Recuperacio.resp.equals(txtRespuesta.getText()))
            {
                
                dispose();
                
                CambioClave camb=new CambioClave();
                camb.setVisible(true);
                
                
            }else{
//                JOptionPane.showMessageDialog (null, "Respuesta Incorrecta");
//                txtRespuesta.setText("");
//                txtRespuesta.requestFocus();
                
            } 
        }
    }  
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnConfirmarUsuario = new javax.swing.JButton();
        btnConfirmarRespuesta = new javax.swing.JButton();
        jpanel_pregun_pane = new javax.swing.JPanel();
        lblpregunta = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("RECUPERACIÓN DE CONTRASEÑA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 11, -1, -1));

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 55, -1, -1));

        jLabel2.setText("Respuesta");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 189, -1, -1));

        jLabel4.setText("Pregunta de Seguridad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 210, -1));

        btnConfirmarUsuario.setText("Confirmar");
        btnConfirmarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 51, -1, -1));

        btnConfirmarRespuesta.setText("Aceptar");
        btnConfirmarRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarRespuestaActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 185, -1, -1));

        jpanel_pregun_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpregunta.setText("¿Como se llamaba tu pimera mascota?");
        jpanel_pregun_pane.add(lblpregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 50));

        getContentPane().add(jpanel_pregun_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 240, 50));
        getContentPane().add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarUsuarioActionPerformed
                // TODO add your handling code here:
             
//         String ced_tra = txtusuario.getText();
//        try{
//            if ("".equals((ced_tra)))
//            {
//                    JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
//                    txtusuario.requestFocus();       
//            }else{
//
//                Connection cn= DriverManager.getConnection("jdbc:mysql://localhost/Usuarios","root","");   
////                String sql= "SELECT * FROM usuarios WHERE usuario='" + txtusuario.getText() + "'";
//////                                     Statement st=con.createStatement();
//            PreparedStatement pst = cn.prepareStatement("select * from usuarios where usaurio = ?");
//            pst.setString(1, txtusuario.getText().trim());
//            ResultSet rs = pst.executeQuery();
//
//        //    PreparedStatement pst = cn.prepareStatement("select * from usuarios where usuario = ?");
//         //   pst.setString(1, txtusuario.getText().trim());
//
//  //          ResultSet rs = pst.executeQuery();
//
//              //busca
//             //  ResultSet rs = st.executeQuery(sql);
//                String preg="";
//                String cedu="";
//                
//                if (rs.next()){
//                    //busca
//                   // cedu=rs.getString("usuario");
//                   // preg=rs.getString("pregunta");
//                    Recuperacio.resp = rs.getString("respuesta");
//                     
//                   
//                } else {
//                    JOptionPane.showConfirmDialog(null, "Nombre de Usuario Incorrecto");
//                    txtusuario.setText("");
//                    txtusuario.requestFocus();
//                }
 //**********************************************************************************************************
                //CONFIGURACION DE PREGUNTA EN EL PANEL 
//                Recuperacio.ced1=cedu;
//               
//                jpanel_pregun_pane.removeAll();
//                jpanel_pregun_pane.updateUI();
//                jpanel_pregun_pane.repaint();                
//                this.validate(); 
//                lblpregunta.setText(preg);
//                jpanel_pregun_pane.setLayout(new GridLayout(1,1));
//                jpanel_pregun_pane.add(lblpregunta);
//                         
//            }               
//        }catch(SQLException | HeadlessException e){          
//        } 
//
//        
//        
        //*******************************************************
        

               try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/Usuarios", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from usuarios where id = ?");
            pst.setString(1, txtid.getText().trim());

            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                txtRespuesta.setText(rs.getString("respuesta"));
                
            } else {
             JOptionPane.showMessageDialog(null, "Persona no registrada.");
            }
        }catch (Exception e){
    }          
    }//GEN-LAST:event_btnConfirmarUsuarioActionPerformed

    private void btnConfirmarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarRespuestaActionPerformed
        // TODO add your handling code here:
        //     Confirmar_Respuesta();

        CambioClave frmRecupera = new CambioClave();
                frmRecupera.setVisible(true);
        
     
    }//GEN-LAST:event_btnConfirmarRespuestaActionPerformed
    
   private void limpiar() {
        txtid.setText("");
        txtRespuesta.setText("");

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recuperacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recuperacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recuperacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recuperacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recuperacio().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarRespuesta;
    private javax.swing.JButton btnConfirmarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jpanel_pregun_pane;
    private javax.swing.JLabel lblpregunta;
    private javax.swing.JPasswordField txtRespuesta;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables

  

  }

