/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Diana
 */
public class Recuperacion extends javax.swing.JInternalFrame {
        public static String resp="";
        public static String ced1="";
    static Object frmReg;
        int x,y;
        static Connection con=null;
    /**
     * Creates new form Recuperacion
     */
    public Recuperacion() {
        initComponents();
        setLocalRelativeTo(null);
       ususa.requestFocus();
    }
    
    
    void Confirmar_Usuario(){
        String ced_tra = ususa.getText();
        try{
            if ("".equals((ced_tra)))
            {
                    JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
                    ususa.requestFocus();
                    
                    
            }else{
   
                String sql= "SELECT * FROM login_usu WHERE nom_usu='"+ususa.getText()+"'";
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(sql);
                String preg="";
                String cedu="";
                
                if (rs.next()){
                    
                    cedu=rs.getString("nom_usu");
                    preg=rs.getString("pregunta");
                    Recuperacion.resp = rs.getString("respuesta");
                    
                   
                } else {
                    JOptionPane.showConfirmDialog(null, "Nombre de Usuario Incorrecto");
                    ususa.setText("");
                    ususa.requestFocus();
                }
                
                //CONFIGURACION DE PREGUNTA EN EL PANEL 
                Recuperacion.ced1=cedu;
               
                jpanel_pregun_pane.removeAll();
                jpanel_pregun_pane.updateUI();
                jpanel_pregun_pane.repaint();
                this.validate(); 
                lblpregunta.setText(preg);
                jpanel_pregun_pane.setLayout(new GridLayout(1,1));
                jpanel_pregun_pane.add(lblpregunta);
                              
            }               
        }catch(HeadlessException | SQLException e){          
        }     
        
        }
    
        void Confirmar_Respuesta(){
        
        String  ced_trans = ususa.getText();
        String  preguu = lblpregunta.getText();
        String  respuu = respuesta.getText();
        
        if(("".equals(ced_trans)) || ("".equals(respuu)) || ("".equals(preguu))){
            JOptionPane.showConfirmDialog(null, "No pueden haber campos vacios");
            respuesta.requestFocus();
            
        } else {
            
            if(Recuperacion.resp.equals(respuesta.getText()))
            {
                dispose();
                Cambio_Clave camb=new Cambio_Clave();
                camb.setVisible(true);
                
                
            }else{
                JOptionPane.showConfirmDialog(null, "Respuesta Incorrecta");
                respuesta.setText("");
                respuesta.requestFocus();
                
            } }}   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ususa = new javax.swing.JTextField();
        respuesta = new javax.swing.JTextField();
        btnConfirmarUsuario = new javax.swing.JButton();
        lblpregunta = new javax.swing.JLabel();
        jpanel_pregun_pane = new javax.swing.JPanel();
        btnConfirmarRespuesta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Usuario");

        jLabel2.setText("Respuesta");

        btnConfirmarUsuario.setText("Confirmar");
        btnConfirmarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarUsuarioActionPerformed(evt);
            }
        });

        lblpregunta.setText("Pregunta de Seguridad");

        javax.swing.GroupLayout jpanel_pregun_paneLayout = new javax.swing.GroupLayout(jpanel_pregun_pane);
        jpanel_pregun_pane.setLayout(jpanel_pregun_paneLayout);
        jpanel_pregun_paneLayout.setHorizontalGroup(
            jpanel_pregun_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );
        jpanel_pregun_paneLayout.setVerticalGroup(
            jpanel_pregun_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnConfirmarRespuesta.setText("Confirmar");
        btnConfirmarRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarRespuestaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("RECUPERACIÓN DE CONTRASEÑA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(lblpregunta))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ususa, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(btnConfirmarUsuario))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(btnConfirmarRespuesta))))
                            .addComponent(jpanel_pregun_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel3)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ususa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarUsuario))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblpregunta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jpanel_pregun_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnConfirmarRespuesta))
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarUsuarioActionPerformed
        // TODO add your handling code here:
        Confirmar_Usuario();
        
    }//GEN-LAST:event_btnConfirmarUsuarioActionPerformed

    private void btnConfirmarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarRespuestaActionPerformed
        // TODO add your handling code here:
        Confirmar_Respuesta();
    }//GEN-LAST:event_btnConfirmarRespuestaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarRespuesta;
    private javax.swing.JButton btnConfirmarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jpanel_pregun_pane;
    private javax.swing.JLabel lblpregunta;
    private javax.swing.JTextField respuesta;
    private javax.swing.JTextField ususa;
    // End of variables declaration//GEN-END:variables

    private void setLocalRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void confirmar_cedula() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
