/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static vista.Recuperacio.con;


/**
 *
 * @author Diana
 */
public class Recuperacion_Contaseña extends javax.swing.JFrame {
    
     public static String ced1="";
    static Object frmReg;
    private static String resp;
        int x,y;
        static Connection con=null;
        
    /** Creates new form Recuperacion_Contaseña */
    public Recuperacion_Contaseña() {
        initComponents();
         txtced_u.requestFocus();
         
    }
     void Confirmar_Usuario(){
         
        String ced_tra = txtced_u.getText();
        try{
            if ("".equals((ced_tra)))
            {
                    JOptionPane.showMessageDialog(null, "No pueden haber campos vacios");
                    txtced_u.requestFocus();
                    
                    
            }else{
              
               //Connection cn= DriverManager.getConnection("jdbc:mysql://localhost/login_usu","root","");
                String sql= "SELECT * FROM  login_usu  WHERE nom_usu='" + txtced_u.getText() + "'";

                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(sql);
                String preg="";
                String cedu="";
                
                if (rs.next()){
                    
                    cedu=rs.getString("nom_usu");
                    preg=rs.getString("pregunta");
                    Recuperacion_Contaseña.resp= rs.getString("respuesta");
                    
                   
                } else {
                    JOptionPane.showConfirmDialog(null, "Nombre de Usuario Incorrecto");
                    txtced_u.setText("");
                    txtced_u.requestFocus();
                }
                
                //CONFIGURACION DE PREGUNTA EN EL PANEL 
                Recuperacion_Contaseña.ced1=cedu;
               
                jpanel_pregun_pane.removeAll();
                jpanel_pregun_pane.updateUI();
                jpanel_pregun_pane.repaint();
                this.validate(); 
                lblpregunta.setText(preg);
                jpanel_pregun_pane.setLayout(new GridLayout(1,1));
                jpanel_pregun_pane.add(lblpregunta);
                              
            }               
        }catch(HeadlessException | SQLException e){          
        }     
        
        }
    
    
        void Confirmar_Respuesta(){
        
        String  ced_trans = txtced_u.getText();
        String  preguu = lblpregunta.getText();
        String  respuu = txtRespuesta.getText();
        
        if(("".equals(ced_trans)) || ("".equals(respuu)) || ("".equals(preguu))){
            JOptionPane.showConfirmDialog(null, "No pueden haber campos vacios");
            txtRespuesta.requestFocus();
            
        } else {
            
            if(Recuperacio.resp.equals(txtRespuesta.getText()))
            {
                dispose();
                Cambio_Clave camb=new Cambio_Clave();
                camb.setVisible(true);
                
                
            }else{
                JOptionPane.showConfirmDialog(null, "Respuesta Incorrecta");
                txtRespuesta.setText("");
                txtRespuesta.requestFocus();
                
            } }} 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        btnConfirmarUsuario = new javax.swing.JButton();
        lblpregunta = new javax.swing.JLabel();
        jpanel_pregun_pane = new javax.swing.JPanel();
        btnConfirmarRespuesta = new javax.swing.JButton();
        txtced_u = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("RECUPERACIÓN DE CONTRASEÑA");

        jLabel1.setText("Usuario");

        jLabel2.setText("Respuesta");

        btnConfirmarUsuario.setText("Confirmar");
        btnConfirmarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarUsuarioActionPerformed(evt);
            }
        });

        lblpregunta.setText("Pregunta de Seguridad");

        jpanel_pregun_pane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpanel_pregun_paneMouseDragged(evt);
            }
        });
        jpanel_pregun_pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanel_pregun_paneMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_pregun_paneLayout = new javax.swing.GroupLayout(jpanel_pregun_pane);
        jpanel_pregun_pane.setLayout(jpanel_pregun_paneLayout);
        jpanel_pregun_paneLayout.setHorizontalGroup(
            jpanel_pregun_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );
        jpanel_pregun_paneLayout.setVerticalGroup(
            jpanel_pregun_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnConfirmarRespuesta.setText("Confirmar");
        btnConfirmarRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarRespuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 36, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addComponent(jLabel1)
                            .addGap(15, 15, 15)
                            .addComponent(txtced_u, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(btnConfirmarUsuario))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblpregunta)
                            .addGap(18, 18, 18)
                            .addComponent(jpanel_pregun_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btnConfirmarRespuesta)))
                    .addGap(0, 37, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel1))
                        .addComponent(txtced_u, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(btnConfirmarUsuario)))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(lblpregunta))
                        .addComponent(jpanel_pregun_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnConfirmarRespuesta))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarUsuarioActionPerformed
        // TODO add your handling code here:
        Confirmar_Usuario();
    }//GEN-LAST:event_btnConfirmarUsuarioActionPerformed

    private void jpanel_pregun_paneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanel_pregun_paneMouseDragged
        // TODO add your handling code here:
        int xp = evt.getXOnScreen()-x;
        int yp = evt.getYOnScreen()-y;
        this.setLocation(xp,yp);

    }//GEN-LAST:event_jpanel_pregun_paneMouseDragged

    private void jpanel_pregun_paneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanel_pregun_paneMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jpanel_pregun_paneMousePressed

    private void btnConfirmarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarRespuestaActionPerformed
        // TODO add your handling code here:
        Confirmar_Respuesta();
    }//GEN-LAST:event_btnConfirmarRespuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recuperacion_Contaseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recuperacion_Contaseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recuperacion_Contaseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recuperacion_Contaseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recuperacion_Contaseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarRespuesta;
    private javax.swing.JButton btnConfirmarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jpanel_pregun_pane;
    private javax.swing.JLabel lblpregunta;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtced_u;
    // End of variables declaration//GEN-END:variables

}
